const SuttaQuotesData = [
   
                { text: `“Công đức người bố thí, \nLuôn luôn được tăng trưởng,\nTrừ được tâm hận thù.\nKhông chất chứa, chế ngự,\nKẻ chí thiện từ bỏ.\nMọi ác hạnh bất thiện,\nDiệt trừ tham, sân, si.\nTâm giải thoát thanh tịnh.”`, ref: "DN 16 – Kinh Đại Bát Niết Bàn", url: "https://loicuaducphat.org/dn/dn16.html#content" },
                { text: `"Hãy tự mình là ngọn đèn cho chính mình, hãy tự mình nương tựa chính mình, chớ nương tựa một gì khác."`, ref: "DN 16 – Kinh Đại Bát Niết Bàn", url: "https://loicuaducphat.org/dn/dn16.html#content" },
			{ text: `"Này các Tỷ-kheo, nếu có người hủy báng Ta, hủy báng Pháp hay hủy báng Tăng, các ngươi chớ có vì vậy sanh lòng công phẫn, tức tối, tâm sanh phiền muộn. Này các Tỷ-kheo, nếu có người hủy báng Ta, hủy báng Pháp hay hủy báng Tăng, và nếu các ngươi sanh lòng công phẫn, tức tối, tâm sanh phiền muộn, thời như vậy sẽ có hại cho các ngươi. Nếu các ngươi công phẫn và phiền muộn, thời các ngươi có thể biết được lời nói của những kẻ ấy là đúng hay sai lạc chăng?"`, ref: "DN 1 – Kinh Phạm Võng ", url: "https://loicuaducphat.org/dn/dn1.html#content" },

             { text: `Này các Tỷ-kheo, Như Lai là bậc A-la-hán, Chánh Ðẳng Giác, thắng tri địa đại là địa đại. Vì thắng tri địa đại là địa đại, Như Lai không nghĩ đến địa đại, không nghĩ đến (tự ngã) đối chiếu với địa đại, không nghĩ đến (tự ngã) như là địa đại, không nghĩ: “Ðịa đại là của ta” - không dục hỷ địa đại. Vì sao vậy? Vì Như Lai biết rằng: “Dục hỷ là căn bản của đau khổ, từ hữu, sanh khởi lên, và già và chết đến với loài sinh vật”. Do vậy, này các Tỷ-kheo, Ta nói vì Như Lai, với sự diệt trừ hoàn toàn các ái, sự ly tham, sự đoạn diệt, sự xả ly, sự từ bỏ hoàn toàn các ái, đã chơn chánh giác ngộ vô thượng chánh đẳng chánh giác.`, ref: "MN 1 – Kinh Pháp Môn Căn Bản", url: "https://loicuaducphat.org/mn/mn1.html#content" },
			 { text: `“Này các Tỷ-kheo, có những lậu hoặc phải do tri kiến được đoạn trừ, có những lậu hoặc phải do phòng hộ được đoạn trừ, có những lậu hoặc phải do thọ dụng được đoạn trừ, có những lậu hoặc phải do kham nhẫn được đoạn trừ, có những lậu hoặc phải do tránh né được đoạn trừ, có những lậu hoặc phải do trừ diệt được đoạn trừ, có những lậu hoặc phải do tu tập được đoạn trừ.”`, ref: "MN 2 – Kinh Tất Cả Lậu Hoặc", url: "https://loicuaducphat.org/mn/mn2.html#content" },

{ text: `“Với người không như lý tác ý, một trong sáu tà kiến này khởi lên: ‘Ta có tự ngã’, tà kiến này khởi lên với người ấy như thật, như chơn; ‘Ta không có tự ngã’, tà kiến này khởi lên với người ấy như thật như chơn; ‘Do tự mình, ta tưởng tri ta có tự ngã’...”\n“Này các Tỷ-kheo, như vậy gọi là tà kiến, kiến trù lâm, kiến hoang vu, kiến hý luận, kiến tranh chấp, kiến kiết phược. Này các Tỷ-kheo, trói buộc bởi kiến kiết sử, kẻ phàm phu ít nghe không được giải thoát khỏi sanh, già, chết, sầu, bi, khổ, ưu, não. Ta nói kẻ ấy không thoát khỏi khổ đau.”`, ref: "MN 2 – Kinh Tất Cả Lậu Hoặc", url: "https://loicuaducphat.org/mn/mn2.html#content" },


               { text: `- Thưa Tôn giả, làm sao Ngài vượt khỏi bộc lưu?\n- Này Hiền giả, không đứng lại, không bước tới, Ta vượt khỏi bộc lưu.\n- Thưa Tôn giả, làm sao không đứng lại, không bước tới, Ngài vượt khỏi bộc lưu?\n- Này Hiền giả, khi Ta đứng lại, thời Ta chìm xuống. Này Hiền giả, khi Ta bước tới, thời Ta trôi giạt; do vậy, này Hiền giả, không đứng lại, không bước tới, Ta vượt khỏi bộc lưu.\n(Vị Thiên):\nTừ lâu, tôi mới thấy\nBà-la-môn tịch tịnh.\nKhông đứng, không bước tới,\nVượt chấp trước ở đời.`, ref: "SN 1.1", url: "https://loicuaducphat.org/sn/sn1.1.html#content" },

{ text: `- Thưa Tôn giả, Ngài có biết giải thoát, thoát ly, viễn ly cho các chúng sanh không?\n- Này Hiền giả, Ta có biết giải thoát, thoát ly, viễn ly cho các chúng sanh.\n- Thưa Tôn giả, như thế nào Ngài biết giải thoát, thoát ly, viễn ly cho các chúng sanh?\nHỷ, tái sanh đoạn tận,\nTưởng, thức được trừ diệt,\nCác thọ diệt, tịch tịnh,\nNhư vậy này Hiền giả,\nTa biết sự giải thoát,\nThoát ly và viễn ly,\nCho các loại chúng sanh.`, ref: "SN 1.2", url: "https://loicuaducphat.org/sn/sn1.2.html#content" },

{ text: `… Ðứng một bên, vị Thiên ấy nói lên bài kệ này trước mặt Thế Tôn:\nMạng sống bị dắt dẫn,\nTuổi thọ chẳng là bao,\nBị dẫn đến già nua,\nKhông có nơi dừng bước.\nAi đem tâm quán tưởng,\nSợ hãi tử vong này,\nHãy làm các công đức,\nÐưa đến chơn an lạc.\n\n(Thế Tôn):\nMạng sống bị dắt dẫn,\nTuổi thọ chẳng là bao,\nBị dẫn đến già nua,\nKhông có nơi dừng bước.\nAi đem tâm quán tưởng,\nSợ hãi tử vong này,\nHãy bỏ mọi thế lợi,\nTâm hướng cầu tịch tịnh.`, ref: "SN 1.3", url: "https://loicuaducphat.org/sn/sn1.3.html#content" },

{ text: `… Nhân duyên ở (Sāvatthi ), đứng một bên, vị Thiên ấy nói lên bài kệ này trước mặt Thế Tôn:\nThời gian lặng trôi qua,\nÐêm ngày luôn di động,\nTuổi tác buổi thanh xuân,\nTiếp tục bỏ chúng ta.\nNhững ai chịu quán sát,\nSợ hãi tử vong này,\nHãy làm các công đức,\nÐưa đến chơn an lạc.\n\n(Thế Tôn):\nThời gian lặng trôi qua,\nÐêm ngày luôn di động,\nTuổi tác buổi thanh xuân,\nTiếp tục bỏ chúng ta.\nNhững ai chịu quán sát,\nSợ hãi tử vong này,\nHãy bỏ mọi thế lợi,\nTâm hướng cầu tịch tịnh.`, ref: "SN 1.4", url: "https://loicuaducphat.org/sn/sn1.4.html#content" },

                { text: `Ta không thấy một sắc nào khác, này các Tỷ-kheo, xâm chiếm và ngự trị tâm người đàn ông như sắc người đàn bà. Này các Tỷ-kheo, sắc người đàn bà xâm chiếm và ngự trị tâm người đàn ông.`, ref: "AN 1.1", url: "https://loicuaducphat.org/an/an1.1.html#content" },

{ text: `Ta không thấy một sắc nào khác, này các Tỷ-kheo, xâm chiếm và ngự trị tâm người đàn bà như sắc người đàn ông. Này các Tỷ-kheo, sắc người đàn ông xâm chiếm và ngự trị tâm người đàn bà.`, ref: "AN 1.6", url: "https://loicuaducphat.org/an/an1.6.html#content" },

{ text: `Ta không thấy một tiếng nào khác, này các Tỷ-kheo, xâm chiếm và ngự trị tâm người đàn ông, như tiếng người đàn bà. Này các Tỷ-kheo, tiếng người đàn bà xâm chiếm và ngự trị tâm người đàn ông.`, ref: "AN 1.2", url: "https://loicuaducphat.org/an/an1.2.html#content" },

{ text: `Ta không thấy một pháp nào khác, này các Tỷ-kheo, dẫn đến dục tham chưa sanh được sanh khởi, hay dục tham đã sanh được tăng trưởng quảng đại, này các Tỷ-kheo, như tịnh tướng. Tịnh tướng, này các Tỷ-kheo, nếu không như lý tác ý, đưa đến dục tham chưa sanh được sanh khởi, hay dục tham đã sanh được tăng trưởng quảng đại.`, ref: "AN 1.11", url: "https://loicuaducphat.org/an/an1.11.html#content" },

{ text: `Ta không thấy một pháp nào khác, này các Tỷ-kheo, đưa đến hôn trầm thụy miên chưa sanh được sanh khởi, hay hôn trầm thụy miên đã sanh được tăng trưởng quảng đại, này các Tỷ-kheo, như không hân hoan, biếng nhác, chán nản, ăn quá no, tâm thụ động. Với người có tâm thụ động, này các Tỷ-kheo, hôn trầm thụy miên chưa sanh được sanh khởi, hay hôn trầm thụy miên đã sanh được tăng trưởng quảng đại.`, ref: "AN 1.13", url: "https://loicuaducphat.org/an/an1.13.html#content" },

{ text: `Ta không thấy một pháp nào khác, này các Tỷ-kheo, đưa đến dục tham chưa sanh không sanh khởi, hay dục tham đã sanh được đoạn tận, này các Tỷ-kheo, như bất tịnh tướng. Bất tịnh tướng, này các Tỷ-kheo, nếu như lý tác ý, thời dục tham chưa sanh không sanh khởi, hay dục tham đã sanh được đoạn tận.`, ref: "AN 1.16", url: "https://loicuaducphat.org/an/an1.16.html#content" },

{ text: `Ta không thấy một pháp nào khác, này các Tỷ-kheo, đưa đến sân chưa sanh không sanh khởi, hay sân đã sanh được đoạn tận, này các Tỷ-kheo, như từ tâm giải thoát. Từ tâm giải thoát, này các Tỷ-kheo, nếu như lý tác ý, thời sân chưa sanh không sanh khởi, hay sân đã sanh được đoạn tận.`, ref: "AN 1.17", url: "https://loicuaducphat.org/an/an1.17.html#content" },

{ text: `Ta không thấy một pháp nào khác, này các Tỷ-kheo, đưa đến hôn trầm thụy miên chưa sanh không sanh khởi, hay hôn trầm thụy miên đã sanh được đoạn tận, này các Tỷ kheo, như tinh cần giới, tinh tấn giới, dõng mãnh giới. Người tinh cần tinh tấn, này các Tỷ kheo, hôn trầm thụy miên chưa sanh không sanh khởi, hay hôn trầm thụy miên đã sanh được đoạn tận.`, ref: "AN 1.18", url: "https://loicuaducphat.org/an/an1.18.html#content" },

                { text: `1. "Ý dẫn đầu các pháp,\nÝ làm chủ, ý tạo;\nNếu với ý ô nhiễm,\nNói lên hay hành động,\nKhổ não bước theo sau,\nNhư xe, chân vật kéo ".\n\n2. "Ý dẫn đầu các pháp,\nÝ làm chủ, ý tạo,\nNếu với ý thanh tịnh,\nNói lên hay hành động,\nAn lạc bước theo sau,\nNhư bóng, không rời hình ".`, ref: "Pháp Cú 1-20", url: "https://loicuaducphat.org/dhp/dhp1-20.html#content" },

{ text: `3. "Nó mắng tôi, đánh tôi,\nNó thắng tôi, cướp tôi "\nAi ôm hiềm hận ấy,\nHận thù không thể nguôi.\n\n4. "Nó mắng tôi, đánh tôi,\nNó thắng tôi, cướp tôi, "\nKhông ôm hiềm hận ấy,\nHận thù được tự nguôi.\n\n5. "Với hận diệt hận thù,\nÐời này không có được.\nKhông hận diệt hận thù,\nLà định luật ngàn thu ".\n\n6. "Người khác không hiểu biết,\nChúng ta đây bị hại.\nChỗ ấy, ai biết được\nTranh luận được lắng êm."\n\n201. "Chiến thắng sinh thù oán,\nThất bại chịu khổ đau,\nSống tịch tịnh an lạc.\nBỏ sau mọi thắng bại."`, ref: "Pháp Cú 1-20", url: "https://loicuaducphat.org/dhp/dhp1-20.html#content" },

{ text: `7. "Ai sống nhìn tịnh tướng,\nkhông hộ trì các căn,\năn uống thiếu tiết độ,\nbiếng nhác, chẳng tinh cần.\nMa uy hiếp kẻ ấy,\nnhư cây yếu trước gió ".\n\n8. "Ai sống quán bất tịnh,\nKhéo hộ trì các căn,\năn uống có tiết độ,\ncó lòng tin, tinh cần,\nMa không uy hiếp được,\nNhư núi đá, trước gió"`, ref: "Pháp Cú 1-20", url: "https://loicuaducphat.org/dhp/dhp1-20.html#content" },

{ text: `9. "Ai mặc áo cà sa,\ntâm chưa rời uế trược,\nkhông tự chế, không thực,\nkhông xứng áo cà sa ".\n\n10. "Ai rời bỏ uế trược,\ngiới luật khéo nghiêm trì,\ntự chế, sống chơn thực,\nthật xứng áo cà sa."`, ref: "Pháp Cú 1-20", url: "https://loicuaducphat.org/dhp/dhp1-20.html#content" },

{ text: `11. "Không chân, tưởng chân thật,\nChân thật, thấy không chân\nHọ không đạt chân thật\nDo tà tư tà hạnh."\n\n12 "Chân thật, biết chân thật,\nKhông chân, biết không chân.\nChúng đạt được chân thật,\ndo chánh tư, chánh hạnh."`, ref: "Pháp Cú 1-20", url: "https://loicuaducphat.org/dhp/dhp1-20.html#content" },

{ text: `13 "Như ngôi nhà vụng lợp,\nMưa liền xâm nhập vào.\nCũng vậy tâm không tu,\nTham dục liền xâm nhập."\n\n14 "Như ngôi nhà khéo lợp,\nMưa không xâm nhập vào.\nCũng vậy tâm khéo tu,\nTham dục không xâm nhập."`, ref: "Pháp Cú 1-20", url: "https://loicuaducphat.org/dhp/dhp1-20.html#content" },

                { text: `Ðứng một bên, vị Thiên tử ấy bạch Thế Tôn với bài kệ:\n\n1. Nhiều Thiên tử và người,\nSuy nghĩ đến điềm lành,\nMong ước và đợi chờ,\nMột nếp sống an toàn,\nXin Ngài hãy nói lên,\nVề điềm lành tối thượng.\n\n2. Không thân cận kẻ ngu,\nNhưng gần gũi bậc Trí,\nÐảnh lễ người đáng lễ,\nLà điềm lành tối thượng.\n\n3. Ở trú xứ thích hợp,\nCông đức trước đã làm,\nChân chánh hướng tự tâm,\nLà điềm lành tối thượng.\n\n4. Học nhiều, nghề nghiệp giỏi,\nKhéo huấn luyện học tập,\nNói những lời khéo nói,\nLà điềm lành tối thượng.\n\n5. Hiếu dưỡng mẹ và cha,\nNuôi nấng vợ và con.\nLàm nghề không rắc rối,\nLà điềm lành tối thượng.\n\n6. Bố thí, hành, đúng pháp,\nSăn sóc các bà con,\nLàm nghiệp không lỗi lầm,\nLà điềm lành tối thượng.`, ref: "Kinh Tiểu Tụng 5", url: "https://loicuaducphat.org/kp/kp5.html#content" },

{ text: `7. Chấm dứt, từ bỏ ác,\nChế ngự đam mê rượu,\nTrong Pháp, không phóng dật,\nLà điềm lành tối thượng.\n\n8. Kính lễ và hạ mình,\nBiết đủ và biết ơn,\nÐúng thời, nghe Chánh Pháp,\nLà điềm lành tối thượng.\n\n9. Nhẫn nhục, lời hòa nhã,\nYết kiến các Sa-môn,\nÐúng thời, đàm luận Pháp,\nLà điềm lành tối thượng.\n\n10. Khắc khổ và Phạm hạnh,\nThấy được lý Thánh đế.\nGiác ngộ quả: "Niết Bàn"\nLà điềm lành tối thượng.\n\n11. Khi xúc chạm việc đời\nTâm không động, không sầu,\nKhông uế nhiễm, an ổn,\nLà điềm lành tối thượng.\n\n12. Làm sự việc như vầy,\nKhông chỗ nào thất bại,\nKhắp nơi được an toàn,\nLà điềm lành tối thượng.`, ref: "Kinh Tiểu Tụng 5", url: "https://loicuaducphat.org/kp/kp5.html#content" },

{ text: `1. Phàm ở tại đời này,\nCó sanh linh tụ hội,\nHoặc trên cõi đất này,\nHoặc chính giữa hư không,\nMong rằng mọi sanh linh,\nÐược đẹp ý vui lòng,\nVậy, hãy nên cẩn thận,\nLắng nghe lời dạy này.\n\n2. Do vậy các sanh linh,\nTất cả hãy chú tâm,\nKhởi lên lòng từ mẫn,\nÐối với thảy mọi loài,\nBan ngày và ban đêm,\nHọ đem vật cúng dường,\nDo vậy không phóng dật,\nHãy giúp hộ trì họ.\n\n3. Phàm có tài sản gì,\nÐời này hay đời sau,\nHay ở tại thiên giới,\nCó châu báu thù thắng,\nKhông gì sánh bằng được,\nVới Như Lai Thiện Thệ,\nNhư vậy, nơi Ðức Phật,\nLà châu báu thù diệu,\nMong với sự thật này,\nÐược sống chơn hạnh phúc.\n\n4. Ðoạn diệt và ly tham,\nBất tử và thù diệu.\nPhật Thích-ca Mâu-ni,\nChứng Pháp ấy trong thiền,\nKhông gì sánh bằng được,\nVới Pháp thù diệu ấy.\nNhư vậy, nơi Chánh Pháp,\nLà châu báu thù diệu,\nMong với sự thật này,\nÐược sống chơn hạnh phúc.`, ref: "Kinh Tiểu Tụng 6", url: "https://loicuaducphat.org/kp/kp6.html#content" },

               { text: `"Do cái này có mặt, cái kia hiện hữu. Do cái này sanh, cái kia sanh. Tức là duyên vô minh, có các hành; duyên các hành, có thức; duyên thức, có danh sắc; duyên danh sắc, có sáu xứ; duyên sáu xứ, có xúc; duyên xúc, có thọ; duyên thọ, có ái; duyên ái, có thủ; duyên thủ, có hữu; duyên hữu, có sanh; duyên sanh, có già, chết, sầu bi khổ ưu não. Như vậy là sự tập khởi của khổ uẩn này".\n\n1. Thật sự, khi các pháp,\nCó mặt, hiện khởi lên,\nÐối vị Bà-la-môn,\nNhiệt tâm hành thiền định,\n\nKhi ấy, với vị ấy,\nCác nghi hoặc tiêu trừ,\nVì biết rõ hoàn toàn,\nPháp cùng với các nhân.`, ref: "Udana 1.1", url: "https://loicuaducphat.org/ud/ud1.1.html#content" },

{ text: `"Do cái này không có mặt, cái kia không hiện hữu. Do cái này diệt, cái kia diệt. Tức là, do vô minh diệt nên hành diệt; do hành diệt, nên thức diệt; do thức diệt, nên danh sắc diệt; do danh sắc diệt nên sáu xứ diệt; do sáu xứ diệt nên xúc diệt, do xúc diệt nên thọ diệt, do thọ diệt, nên ái diệt; do ái diệt, nên thủ diệt; do thủ diệt, nên hữu diệt; do hữu diệt, nên sanh diệt; do sanh diệt, nên già, chết, sầu, bi, khổ, ưu não diệt. Như vậy là đoạn diệt của khổ uẩn này".\n\n2. Thật sự khi các pháp,\nCó mặt, hiện khởi lên,\nÐối với vị Bà-la-môn,\nNhiệt tâm, hành thiền định,\n\nKhi ấy, với vị ấy,\nCác nghi hoặc tiêu trừ,\nVì đã biết hoàn toàn,\nSự chấm dứt các duyên.`, ref: "Udana 1.2", url: "https://loicuaducphat.org/ud/ud1.2.html#content" },

{ text: `3. Thật sự khi các pháp\nCó mặt, hiện khởi lên,\nÐối với vị Bà-la-môn,\nNhiệt tâm hành thiền định,\n\nQuét sạch các ma quân,\nVị ấy đứng, an trú,\nNhư ánh sáng mặt trời,\nChói sáng khắp hư không.`, ref: "Udana 1.3", url: "https://loicuaducphat.org/ud/ud1.3.html#content" },

{ text: `- Tôn giả Gotama, cho đến như thế nào là Bà-la-môn, và những pháp nào tác thành Bà-la-môn? Thế Tôn sau khi biết được ý nghĩa này, ngay trong lúc ấy, nói lên lời cảm hứng này:\n\n4. Vị Bà-la-môn nào,\nLoại trừ các ác pháp,\nKhông kiêu, không uế nhiễm,\nTự ngã khéo chế ngự,\nVệ-đà được thông đạt,\nPhạm hạnh được viên thành,\n\nVị Bà-la-môn ấy,\nCó thể nói lên được,\nLời Phạm ngữ đúng pháp,\nVị ấy ở đời này,\nKhông hề có mạn tâm\nBất cứ ở nơi nào.`, ref: "Udana 1.4", url: "https://loicuaducphat.org/ud/ud1.4.html#content" },

                { text: `Này các Tỷ-kheo, hãy từ bỏ một pháp. Ta bảo đảm cho các Thầy không có tái sanh. Thế nào là một pháp? Tham, này các Tỷ-kheo, là một pháp, các Thầy hãy từ bỏ! Ta bảo đảm cho các Thầy không có tái sanh. Thế Tôn đã nói lên ý nghĩa này. Ở đây, điều này đã được nói đến.\n\nVới tham bị tham đắm,\nChúng sanh đi ác thú,\nBậc thiền quán, chánh trí,\nTừ bỏ tham ái ấy,\nTừ bỏ, không bao giờ\nTrở lại tại đời này.`, ref: "Itivuttaka 1", url: "https://loicuaducphat.org/iti/iti1.html#content" },
{ text: `Này các Tỷ-kheo, hãy từ bỏ một pháp. Ta bảo đảm cho các Thầy không có tái sanh. Thế nào là một pháp? Mạn, này các Tỷ kheo, là một pháp các Thầy hãy từ bỏ. Ta bảo đảm cho các Thầy không có tái sanh. Thế Tôn đã nói lên ý nghĩa này. Ở đây, điều này được nói đến.\n\nVới kiêu mạn kiêu căng,\nChúng sanh đi ác thú,\nBậc thiền quán, chánh trí\nTừ bỏ kiêu mạn ấy,\nTừ bỏ, không bao giờ\nTrở lại tại đời này.`, ref: "Itivuttaka 6", url: "https://loicuaducphat.org/iti/iti6.html#content" },

{ text: `Này các Tỷ-kheo, ai không thắng tri, không liễu tri tất cả, ở đây tâm không ly tham, từ bỏ, không thể diệt được khổ đau. Này các Tỷ-kheo, ai thắng tri, liễu tri tất cả, ở đây tâm ly tham, từ bỏ, có thể diệt được khổ đau. Thế Tôn đã nói lên ý nghĩa này. Ở đây, điều này được nói đến.\n\nAi hiểu, rõ biết được,\nTất cả là tất cả,\nÐối với tất cả chỗ,\nKhông có sự tham đắm,\nVị như vậy chắc chắn,\nLiễu tri được tất cả,\nVà có thể vượt qua,\nTất cả mọi đau khổ.`, ref: "Itivuttaka 7", url: "https://loicuaducphat.org/iti/iti7.html#content" },

{ text: `Này các Tỷ-kheo, ai không thắng tri không liễu tri Mạn, ở đây tâm không ly tham, không từ bỏ, thời không có thể diệt được khổ đau. Này các Tỷ-kheo, ai thắng tri liễu tri Mạn, ở đây tâm ly tham, từ bỏ, có thể diệt được khổ đau. Thế Tôn đã nói lên ý nghĩa này. Ở đây, điều này đã được nói đến.\n\nNgười bị mạn chi phối,\nDo bị mạn trói buộc,\nNên hoan hỷ sanh hữu,\nDo không liễu tri mạn,\nNên đi đến tái sanh.\n\nNhững ai đoạn diệt mạn,\nGiải thoát, mạn hoại diệt,\nHọ thắng mạn trói buộc,\nHọ vượt qua nhiếp phục,\nTất cả mọi đau khổ.`, ref: "Itivuttaka 8", url: "https://loicuaducphat.org/iti/iti8.html#content" },

{ text: `Này các Tỷ-kheo, Ta không thấy một triền cái nào khác, do bị bao trùm bởi triền cái ấy, chúng sanh trong một thời gian dài, lưu chuyển. Này các Tỷ-kheo, tức là Vô minh triền cái. Này các Tỷ-kheo, bị bao trùm bởi Vô minh triền cái, chúng sanh trong một thời gian dài chạy dài, lưu chuyển.\n\nKhông có một pháp khác,\nQuần sanh bị bao phủ,\nNgày đêm chạy lưu chuyển,\nNhư bao phủ bởi si.\n\nVà ai đoạn diệt si,\nÐâm thủng khối u ám,\nHọ không lưu chuyển nữa,\nTrong họ, nhân không còn.`, ref: "Itivuttaka 14", url: "https://loicuaducphat.org/iti/iti14.html#content" },

{ text: `Này các Tỷ-kheo, Ta không thấy một kiết sử nào khác, do bị cột bởi kiết sử ấy, chúng sanh trong một thời gian dài, chạy dài, lưu chuyển, này các Tỷ-kheo tức là Ái kiết sử. Này các Tỷ-kheo, bị cột với ái kiết sử, chúng sanh trong một thời gian dài, chạy dài lưu chuyển.\n\nNgười có ái làm bạn,\nThời gian dài, lưu chuyển,\nKhông vượt được lưu chuyển,\nSanh hữu vậy hay khác.\n\nAi biết nguy hiểm này,\nBiết ái tác thành khổ,\nBỏ ái, không chấp trước,\nTỷ-kheo giữ chánh niệm,\nBỏ gia đình xuất gia,\nSống nếp sống như vậy.`, ref: "Itivuttaka 15", url: "https://loicuaducphat.org/iti/iti15.html#content" },

                { text: `1. Ai nhiếp phục phẫn nộ\nÐang được dấy khởi lên,\nNhư dùng chất linh dược,\nNgăn độc rắn lan rộng\nTỷ-kheo ấy từ bỏ,\nBờ này và bờ kia,\nNhư loài rắn thoát bỏ\nDa rắn cũ già xưa.\n\n2. Ái cắt đứt tham dục,\nKhông còn chút dư tàn,\nNhư kẻ hái hoa sen\nSanh ra từ ao hồ.\nTỷ-kheo ấy từ bỏ,\nBờ này và bờ kia,\nNhư loài rắn thoát bỏ\nDa rắn cũ già xưa.`, ref: "Kinh Tập 1.1", url: "https://loicuaducphat.org/snp/snp1.1.html#content" },

{ text: `3. Ai cắt đứt tham ái,\nKhông còn chút dư tàn,\nLàm cho nước cạn khô,\nDòng nước chảy nhanh mạnh\nTỷ-kheo ấy từ bỏ,\nBờ này và bờ kia,\nNhư loài rắn thoát bỏ\nDa rắn cũ già xưa.\n\n4. Ai phá hoại kiêu mạn\nKhông còn chút dư tàn,\nNhư nước mạnh tàn phá\nCây cỏ lau yếu hèn,\nTỷ-kheo ấy từ bỏ,\nBờ này và bờ kia,\nNhư loài rắn thoát bỏ\nDa rắn cũ già xưa.`, ref: "Kinh Tập 1.1", url: "https://loicuaducphat.org/snp/snp1.1.html#content" },

{ text: `5. Ai trong các sanh hữu,\nKhông tìm thấy lõi cây,\nNhư kẻ đi hái hoa,\nTrên cây sung không hoa.\nTỷ-kheo ấy từ bỏ,\nBờ này và bờ kia,\nNhư loài rắn thoát bỏ\nDa rắn cũ già xưa.\n\n6. Với ai trong nội tâm,\nKhông còn có phẫn hận,\nÐã vượt thoát ra khỏi,\nCả hữu và phi hữu.\nTỷ-kheo ấy từ bỏ,\nBờ này và bờ kia,\nNhư loài rắn thoát bỏ\nDa rắn cũ già xưa.\n\n7. Với ai những tầm tư,\nÐược làm cho tan biến\nNội tâm khéo sửa soạn,\nKhông còn chút dư tàn.\nTỷ-kheo ấy từ bỏ,\nBờ này và bờ kia,\nNhư loài rắn thoát bỏ\nDa rắn cũ già xưa.`, ref: "Kinh Tập 1.1", url: "https://loicuaducphat.org/snp/snp1.1.html#content" },

{ text: `8. Ai không đi quá trớn,\nCũng không quá chậm trễ,\nÐã nhiếp phục toàn diện,\nHý luận chướng ngại này.\nTỷ-kheo ấy từ bỏ,\nBờ này và bờ kia,\nNhư loài rắn thoát bỏ\nDa rắn cũ già xưa.\n\n9. Ai không đi quá trớn,\nCũng không quá chậm trễ,\nBiết rõ được ở đời,\nSự này toàn hư vọng.\nTỷ-kheo ấy từ bỏ,\nBờ này và bờ kia,\nNhư loài rắn thoát bỏ\nDa rắn cũ già xưa.\n\n10. Ai không đi quá trớn,\nCũng không quá chậm trễ,\nTừ bỏ, không có tham,\nSự này toàn hư vọng.\nTỷ-kheo ấy từ bỏ,\nBờ này và bờ kia,\nNhư loài rắn thoát bỏ\nDa rắn cũ già xưa.`, ref: "Kinh Tập 1.1", url: "https://loicuaducphat.org/snp/snp1.1.html#content" },

                { text: `Trưởng Lão Subhuti\n\n1. Am thất ta khéo lợp,\nAn lạc, ngăn chận gió,\nThần mưa, hãy mưa đi,\nMưa như ý Ngươi muốn!\nTâm ta khéo định tĩnh,\nGiải thoát, sống tinh cần,\nThần mưa, hãy mưa đi!`, ref: "Trưởng Lão Tăng Kệ 1.1", url: "https://loicuaducphat.org/thag/thag1.1.html#content" },

{ text: `Trưởng Lão Mahakotthita\n\n2. Tịch tịnh và chỉ tức,\nTụng đọc lời trí tuệ,\nTâm tư không tháo động,\nÁc pháp được vứt bỏ,\nGiống như những lá cây,\nBị gió thổi phiêu bạt.`, ref: "Trưởng Lão Tăng Kệ 1.2", url: "https://loicuaducphat.org/thag/thag1.2.html#content" },

{ text: `Trưởng Lão Kankha-Revata\n\n3. Hãy thấy trí tuệ này\nCủa những bậc Như Lai,\nNhư lửa cháy nửa đêm,\nCho ánh sáng, cho mắt,\nHọ nhiếp phục nghi ngờ\nCho những ai đi đến.`, ref: "Trưởng Lão Tăng Kệ 1.3", url: "https://loicuaducphat.org/thag/thag1.3.html#content" },

{ text: `Trưởng Lão Punna Mantaniputta\n\n4. Hãy thân cận người hiền,\nBậc hiền minh thấy nghĩa,\nNghĩa lớn và thâm sâu,\nKhó thấy, tế, tế nhị,\nBậc trí chứng đạt được,\nKhông phóng dật, chú tâm.`, ref: "Trưởng Lão Tăng Kệ 1.4", url: "https://loicuaducphat.org/thag/thag1.4.html#content" },

                { text: `Trưởng Lão Ni Muttà\n\n2. Hỡi này, giải thoát Ni\nHãy giải thoát các ách,\nNhư mặt trăng thoát khỏi,\nMiệng hàm của Ràhu,\nVới tâm tư giải thoát,\nKhỏi nợ nần trói buộc,\nHãy thọ hưởng món ăn,\nDo khất thực đem lại.`, ref: "Trưởng Lão Ni Kệ 1.2", url: "https://loicuaducphat.org/thig/thig1.2.html#content" },

{ text: `Trưởng Lão Ni Punnà\n\n3. Hỡi này, thành Mãn ni,\nHãy tràn đầy Chánh pháp,\nNhư mặt trăng tròn đầy,\nTrong ngày rằm trăng tròn,\nHãy tràn đầy trí tuệ,\nPhá tan khối si ám.`, ref: "Trưởng Lão Ni Kệ 1.3", url: "https://loicuaducphat.org/thig/thig1.3.html#content" },

{ text: `Trưởng Lão Ni Tissà\n\n4. Tissà hãy học tập,\nHọc trong những học pháp,\nChớ để cho các ách,\nVượt khỏi chi phối nàng.\nHãy sống không liên hệ,\nMọi ách không trói buộc,\nSống giữa thế giới này,\nKhông có các lậu hoặc.`, ref: "Trưởng Lão Ni Kệ 1.4", url: "https://loicuaducphat.org/thig/thig1.4.html#content" },

{ text: `Một Trưởng Lão Ni Tissà Khác\n\n5. Tissà, hãy cột tâm\nTập trung trên các pháp,\nChớ để từng sát-na\nUổng phí vượt khỏi nàng!\nNhững sát-na đã qua\nHọ sầu muộn, đau khổ,\nKhi họ bị rơi vào\nTrong cảnh giới địa ngục.`, ref: "Trưởng Lão Ni Kệ 1.5", url: "https://loicuaducphat.org/thig/thig1.5.html#content" },

{ text: `Trưởng Lão Ni Dhìra\n\n6. Dhìra, hãy cảm xúc,\nNhững cảm chứng đoạn diệt,\nTịnh chỉ các vọng tưởng,\nLà chân chánh an lạc,\nHãy thuận hướng Niết-bàn,\nÁch an ổn, vô thường.`, ref: "Trưởng Lão Ni Kệ 1.6", url: "https://loicuaducphat.org/thig/thig1.6.html#content" },

{ text: `Một Trưởng Lão Ni Dhìra Khác\n\n7. Dhìra, hãy kiên trì,\nNắm giữ các thiện pháp,\nHỡi này Tỷ-kheo-ni,\nCác căn được tu tập,\nHãy mang cái thân này,\nLà cái thân cuối cùng,\nSau khi đã chiến thắng,\nÁc ma nữ quân lực,\nSau khi đã chiến thắng,\nÁc ma với quân lực.`, ref: "Trưởng Lão Ni Kệ 1.7", url: "https://loicuaducphat.org/thig/thig1.7.html#content" },

{ text: `Trưởng Lão Ni Mittà\n\n8. Hỡi này Mittà bạn!\nVới lòng tin xuất gia,\nHãy tu tập rèn luyện,\nHân hoan trong bạn lành,\nHãy tu tập rèn luyện,\nTrong các pháp hiếu thiện,\nCố gắng đạt cho được,\nAn ổn khỏi ách nạn.`, ref: "Trưởng Lão Ni Kệ 1.8", url: "https://loicuaducphat.org/thig/thig1.8.html#content" },

{ text: `Trưởng Lão Ni Bhadhà\n\n9. Hỡi Bhàdha hiền thiện,\nVới lòng tin xuất gia,\nHãy sống vui hoan hỷ,\nTrong các pháp hiền thiện,\nHãy tu tập rèn luyện,\nTrong các pháp chí thiện,\nCố gắng đạt cho được,\nAn ổn khỏi ách nạn.`, ref: "Trưởng Lão Ni Kệ 1.9", url: "https://loicuaducphat.org/thig/thig1.9.html#content" },

         
        ];

       module.exports = { SuttaQuotesData };